"""init

Revision ID: 781c26d3e6a2
Revises: 
Create Date: 2025-12-19 22:35:08.990459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # <--- 1. Import ini ditambahkan

# revision identifiers, used by Alembic.
revision: str = '781c26d3e6a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # <--- 2. PERBAIKAN: Membuat Type ENUM secara manual sebelum digunakan ---
    event_status_enum = postgresql.ENUM(
        'DRAFT', 'PUBLISHED', 'ENDED', name='eventstatus')
    event_status_enum.create(op.get_bind(), checkfirst=True)
    # -----------------------------------------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_phases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('price', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('quota', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('bookings', sa.Column(
        'phase_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column(
        'checked_in_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'ticket_phases', [
                          'phase_id'], ['id'])

    op.add_column('events', sa.Column('image_url', sa.Text(), nullable=True))

    # Menggunakan Enum yang sudah didefinisikan namanya
    op.add_column('events', sa.Column('status', sa.Enum(
        'DRAFT', 'PUBLISHED', 'ENDED', name='eventstatus'), nullable=True))

    op.drop_column('events', 'ticket_price')
    op.add_column('users', sa.Column(
        'nik', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('phone_number',
                  sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['nik'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'nik')
    op.add_column('events', sa.Column('ticket_price', sa.NUMERIC(
        precision=10, scale=2), autoincrement=False, nullable=False))

    op.drop_column('events', 'status')

    op.drop_column('events', 'image_url')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'checked_in_at')
    op.drop_column('bookings', 'phase_id')
    op.drop_table('ticket_phases')
    # ### end Alembic commands ###

    # <--- 3. PERBAIKAN: Menghapus Type ENUM setelah kolomnya dihapus ---
    event_status_enum = postgresql.ENUM(
        'DRAFT', 'PUBLISHED', 'ENDED', name='eventstatus')
    event_status_enum.drop(op.get_bind(), checkfirst=True)
    # -------------------------------------------------------------------
