"""add many thing

Revision ID: 9f8e1f8e18af
Revises: e9c2d99db35e
Create Date: 2025-12-18 22:14:22.145562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8e1f8e18af'
down_revision: Union[str, Sequence[str], None] = 'e9c2d99db35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ENDED', name='eventstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'published'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ENDED', name='eventstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'published'::character varying"))
    # ### end Alembic commands ###
